### ISSUE TITLE
[PT2.2] API posting

### ISSUE THREAD

**Issue by HojouFotytu** [PTMagicians/PTMagic#17]
Receiving this error when PTM tries to send settings files via API:

2018/12/15 20:17:51.533 INFO - Sending PAIRS.properties...

2018/12/15 20:17:52.686 FATAL - Saving PAIRS.properties failed for setting 'default': The remote server returned an error: (400) Required String parameter 'saveData' is not present. System.Net.WebException The remote server returned an error: (400) Required String parameter 'saveData' is not present.    at System.Net.HttpWebRequest.GetResponse()
   at Core.ProfitTrailer.SettingsAPI.SendPropertyLinesToAPI(String ptFileName, List`1 lines, PTMagicConfiguration systemConfiguration, LogHelper log) in G:\PTM Dev Bot\PTMagic Github Clone\PTMagic\Core\ProfitTrailer\SettingsAPI.cs:line 131

**Comment by HojouFotytu** [comment]
After fixing this with the correct API command, rather than a "filename" the api now requires "pairsDATA", "dcaDATA" and "indicatorsDATA" for the setting names.
